/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author cr075
 */
public class EdtCursos extends javax.swing.JInternalFrame {

    /**
     * Creates new form RgtEstudiante
     */
    public EdtCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNom = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNom.setBackground(new java.awt.Color(255, 255, 255));
        txtNom.setPreferredSize(new java.awt.Dimension(872, 736));
        txtNom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar Curso");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 430, 40));

        txtNom.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 780, 90));
        txtNom.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Información General del Curso");
        txtNom.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, -1));
        txtNom.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 480, 10));

        btnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(null);
        btnActualizar.setOpaque(true);
        txtNom.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setOpaque(true);
        txtNom.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Código: ");
        txtNom.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Nombre del Curso: ");
        txtNom.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, 40));

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNom.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 200, 30));

        txtCod.setBackground(new java.awt.Color(204, 204, 204));
        txtCod.setBorder(null);
        txtNom.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 30));

        getContentPane().add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 775, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtCod;
    public javax.swing.JPanel txtNom;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
