/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Procesos.ProcesosHorario;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author cr075
 */
public class EdtHorario extends javax.swing.JInternalFrame {

    /**
     * Creates new form RgtEstudiante
     */
    public EdtHorario() {
        initComponents();
        InicializarCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnVerificarSalon = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtNombreCurso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnVerificarCurso = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtNombreProf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnVerificarProf = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSeccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        spnHoraFin = new javax.swing.JSpinner();
        spnHoraIni = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        chkLunes = new javax.swing.JCheckBox();
        chkMartes = new javax.swing.JCheckBox();
        chkMier = new javax.swing.JCheckBox();
        chkJue = new javax.swing.JCheckBox();
        chkVie = new javax.swing.JCheckBox();
        txtCod = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblSeccion = new javax.swing.JLabel();
        cbxCodSalon = new javax.swing.JComboBox<>();
        cbxCodCurso = new javax.swing.JComboBox<>();
        cbxDniProf = new javax.swing.JComboBox<>();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(880, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(880, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(875, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 200, 130));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar Horario de c. Grado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 650, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 880, 110));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Verificar información del Grado y Sección a registrar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 310, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 480, 10));

        btnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("REGISTRAR");
        btnActualizar.setBorder(null);
        btnActualizar.setOpaque(true);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setOpaque(true);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Código de salón: *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 40));

        txtGrado.setBackground(new java.awt.Color(204, 204, 204));
        txtGrado.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtGrado.setBorder(null);
        txtGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradoActionPerformed(evt);
            }
        });
        jPanel1.add(txtGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 130, 30));

        jLabel6.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel6.setText("Grado: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, 40));

        btnVerificarSalon.setBackground(new java.awt.Color(204, 204, 204));
        btnVerificarSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/cheque.png"))); // NOI18N
        btnVerificarSalon.setBorder(null);
        jPanel1.add(btnVerificarSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 50, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 70, 20));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel4.setText("Verificar Información del Curso a registrar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 250, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 540, 10));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Código de curso:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 40));

        txtNombreCurso.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreCurso.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNombreCurso.setBorder(null);
        txtNombreCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCursoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 130, 30));

        jLabel9.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel9.setText("Curso: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 40));

        btnVerificarCurso.setBackground(new java.awt.Color(204, 204, 204));
        btnVerificarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/cheque.png"))); // NOI18N
        btnVerificarCurso.setBorder(null);
        btnVerificarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarCursoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerificarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 50, 30));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 70, 10));

        jLabel10.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel10.setText("Verificar Información del Profesor a registrar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 270, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 530, 10));

        jLabel11.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel11.setText("N° Dni:*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));

        txtNombreProf.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreProf.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNombreProf.setBorder(null);
        txtNombreProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProfActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 130, 30));

        jLabel12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel12.setText("Nombre: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, 40));

        btnVerificarProf.setBackground(new java.awt.Color(204, 204, 204));
        btnVerificarProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/cheque.png"))); // NOI18N
        btnVerificarProf.setBorder(null);
        jPanel1.add(btnVerificarProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 50, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 70, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 540, 10));

        jLabel14.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel14.setText("Día:* ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 40));

        jLabel15.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel15.setText("Hora de fin:*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, 40));

        txtSeccion.setBackground(new java.awt.Color(204, 204, 204));
        txtSeccion.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtSeccion.setBorder(null);
        txtSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 100, 30));

        jLabel16.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel16.setText("Sección: ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, 40));

        jLabel17.setFont(new java.awt.Font("Swis721 Ex BT", 1, 11)); // NOI18N
        jLabel17.setText("Asignar Horario del Grado y Sección: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 260, -1));

        jLabel19.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel19.setText("Hora de inicio:*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, -1, 40));
        jPanel1.add(spnHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 90, -1));
        jPanel1.add(spnHoraIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 90, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkLunes.setText("Lunes");
        jPanel3.add(chkLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        chkMartes.setText("Martes");
        chkMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMartesActionPerformed(evt);
            }
        });
        jPanel3.add(chkMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        chkMier.setText("Miércoles");
        jPanel3.add(chkMier, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        chkJue.setText("Jueves");
        jPanel3.add(chkJue, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        chkVie.setText("Viernes");
        jPanel3.add(chkVie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 170, 140));

        txtCod.setBackground(new java.awt.Color(204, 204, 204));
        txtCod.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCod.setBorder(null);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 30));

        jLabel20.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel20.setText("Código: *");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 40));

        lblCurso.setFont(new java.awt.Font("Swis721 Ex BT", 1, 11)); // NOI18N
        jPanel1.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 50, 20));

        lblSeccion.setFont(new java.awt.Font("Swis721 Ex BT", 1, 11)); // NOI18N
        jPanel1.add(lblSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 50, 20));

        cbxCodSalon.setBackground(new java.awt.Color(204, 204, 204));
        cbxCodSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCodSalonActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCodSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, 30));

        cbxCodCurso.setBackground(new java.awt.Color(204, 204, 204));
        cbxCodCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCodCursoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCodCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 140, 30));

        cbxDniProf.setBackground(new java.awt.Color(204, 204, 204));
        cbxDniProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDniProfActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDniProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicializarCombos(){
        ProcesosHorario.LlenarComboDesdeCursos(cbxCodCurso);
        ProcesosHorario.LlenarComboDesdeProfesores(cbxDniProf);
        ProcesosHorario.LlenarComboDesdeSalones(cbxCodSalon);
    }
   public void configurarSpinnerHora() {
    // Crear un modelo de fecha para el JSpinner
    SpinnerDateModel modelin = new SpinnerDateModel();
    SpinnerDateModel modelfin = new SpinnerDateModel();

    // Establecer el valor inicial en las 8:00 (sin segundos)
    Calendar cal = Calendar.getInstance();
    cal.set(Calendar.HOUR_OF_DAY, 8); // Hora inicial
    cal.set(Calendar.MINUTE, 0);      // Minutos iniciales
    cal.set(Calendar.SECOND, 0);      // Asegurar que los segundos sean 0
    Date horaInicial = cal.getTime();

    modelin.setValue(horaInicial); // Configurar hora inicial
    modelfin.setValue(horaInicial);

    // Asignar el modelo al JSpinner
    spnHoraIni.setModel(modelin);
    spnHoraFin.setModel(modelfin);

    // Configurar el editor para mostrar solo horas y minutos
    JSpinner.DateEditor editorini = new JSpinner.DateEditor(spnHoraIni, "HH:mm");
    JSpinner.DateEditor editorfin = new JSpinner.DateEditor(spnHoraFin, "HH:mm");

    spnHoraIni.setEditor(editorini);
    spnHoraFin.setEditor(editorfin);
}


   
    private void txtGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradoActionPerformed

    private void txtNombreCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCursoActionPerformed

    private void txtNombreProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProfActionPerformed

    private void txtSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeccionActionPerformed

    private void chkMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMartesActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
             
        /**
         public void actionPerformed(ActionEvent e) {
        // Obtén los días seleccionados
         List<String> diasSeleccionados = new ArrayList<>();

        if(chkLunes.isSelected()) {
            diasSeleccionados.add("Lunes");
        }
        if(chkMartes.isSelected()) {
            diasSeleccionados.add("Martes");
        }
        if(chkMiercoles.isSelected()) {
            diasSeleccionados.add("Miércoles");
        }
        if(chkJueves.isSelected()) {
            diasSeleccionados.add("Jueves");
        }
        if(chkViernes.isSelected()) {
            diasSeleccionados.add("Viernes");
        }
        if(chkSabado.isSelected()) {
            diasSeleccionados.add("Sábado");
        }
        if(chkDomingo.isSelected()) {
            diasSeleccionados.add("Domingo");
        }

      
        // Obtén la hora de inicio y fin (suponiendo que usas los JSpinner)
        Date horaInicio = (Date) spinnerHoraInicio.getValue();
        Date horaFin = (Date) spinnerHoraFin.getValue();

        // Realiza el registro (aquí puedes integrar tu lógica de base de datos)
        System.out.println("Días seleccionados: " + diasSeleccionados);
        System.out.println("Hora de inicio: " + horaInicio);
        System.out.println("Hora de fin: " + horaFin);
        }**/

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void cbxCodSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCodSalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCodSalonActionPerformed

    private void cbxCodCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCodCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCodCursoActionPerformed

    private void cbxDniProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDniProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDniProfActionPerformed

    private void btnVerificarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnVerificarCurso;
    public javax.swing.JButton btnVerificarProf;
    public javax.swing.JButton btnVerificarSalon;
    public javax.swing.JComboBox<String> cbxCodCurso;
    public javax.swing.JComboBox<String> cbxCodSalon;
    public javax.swing.JComboBox<String> cbxDniProf;
    public javax.swing.JCheckBox chkJue;
    public javax.swing.JCheckBox chkLunes;
    public javax.swing.JCheckBox chkMartes;
    public javax.swing.JCheckBox chkMier;
    public javax.swing.JCheckBox chkVie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JLabel lblCurso;
    public javax.swing.JLabel lblSeccion;
    public javax.swing.JSpinner spnHoraFin;
    public javax.swing.JSpinner spnHoraIni;
    public javax.swing.JTextField txtCod;
    public javax.swing.JTextField txtGrado;
    public javax.swing.JTextField txtNombreCurso;
    public javax.swing.JTextField txtNombreProf;
    public javax.swing.JTextField txtSeccion;
    // End of variables declaration//GEN-END:variables
}
