/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.ButtonGroup;

/**
 *
 * @author cr075
 */
public class EdtProfesor extends javax.swing.JInternalFrame {
    public ButtonGroup groupSex ;
    /**
     * Creates new form RgtEstudiante
     */
    public EdtProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cbxDoc = new javax.swing.JComboBox<>();
        txtDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cbxPais = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        rdbFem = new javax.swing.JRadioButton();
        rdbMas = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtAñosExperiencia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        cbxAcademico = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbxDispHoraria = new javax.swing.JComboBox<>();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtInstiAnteriores = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        cbxEspecializacion = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar Profesor");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 430, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 860, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Información General del Profesor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 560, 10));

        cbxDoc.setBackground(new java.awt.Color(204, 204, 204));
        cbxDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dni", "Pasaporte" }));
        cbxDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDocActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 30));

        txtDoc.setBackground(new java.awt.Color(204, 204, 204));
        txtDoc.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtDoc.setBorder(null);
        txtDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocActionPerformed(evt);
            }
        });
        jPanel1.add(txtDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 240, 30));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel4.setText("N° de Documento:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 40));

        btnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(null);
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de Documento:*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));

        txtNombres.setBackground(new java.awt.Color(204, 204, 204));
        txtNombres.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 260, 30));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Nombres:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 40));

        txtApellido.setBackground(new java.awt.Color(204, 204, 204));
        txtApellido.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtApellido.setBorder(null);
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 280, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, 10));

        jLabel8.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel8.setText("Datos de Nacimiento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 210, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 630, 10));

        jLabel11.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel11.setText("Fecha:* ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 40));

        cbxPais.setBackground(new java.awt.Color(204, 204, 204));
        cbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Peru", "Otro" }));
        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 190, 30));

        jLabel15.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel15.setText("Apellidos:*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 40));

        rdbFem.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rdbFem.setText("Femenino");
        rdbFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFemActionPerformed(evt);
            }
        });
        jPanel1.add(rdbFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        rdbMas.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rdbMas.setText("Masculino");
        jPanel1.add(rdbMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel20.setText("País:*");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 70, 10));

        jLabel21.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel21.setText("Datos de Contacto");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 120, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 660, 10));

        txtAñosExperiencia.setBackground(new java.awt.Color(204, 204, 204));
        txtAñosExperiencia.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtAñosExperiencia.setBorder(null);
        jPanel1.add(txtAñosExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 70, 30));

        jLabel24.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel24.setText("Correo o N° Contacto:* ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 40));

        txtContacto.setBackground(new java.awt.Color(204, 204, 204));
        txtContacto.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtContacto.setBorder(null);
        jPanel1.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 240, 30));

        jLabel12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel12.setText("Sexo:*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 70, 10));

        jLabel17.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel17.setText("Formación Academica");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 210, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 630, 10));

        cbxAcademico.setBackground(new java.awt.Color(204, 204, 204));
        cbxAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1 Grado", "2 Grado", "3 Grado", "4 Grado", "5 Grado" }));
        cbxAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAcademicoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 170, 30));

        jLabel18.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel18.setText("Grado Académico:* ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 150, 40));

        jLabel19.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel19.setText("Especialización:*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 110, 40));

        cbxDispHoraria.setBackground(new java.awt.Color(204, 204, 204));
        cbxDispHoraria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "8:00-10:00", "10:00-12:00", "12:00-14:00" }));
        cbxDispHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDispHorariaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDispHoraria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 140, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 70, 10));

        jLabel25.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel25.setText("Experiencia Laboral");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 120, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 650, 10));

        jLabel26.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel26.setText("Disponibilidad Horaria:* ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, 40));

        jLabel27.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel27.setText("Instituciones Anteriores:*");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, 40));

        jLabel28.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel28.setText("Años de Experiencia:*");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, 40));

        txtInstiAnteriores.setBackground(new java.awt.Color(204, 204, 204));
        txtInstiAnteriores.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtInstiAnteriores.setBorder(null);
        jPanel1.add(txtInstiAnteriores, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 140, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 640, 10));

        jLabel30.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel30.setText("Documentos Adjuntos");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 150, -1));

        jLabel31.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel31.setText("Curriculum Vitae:*");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, 40));

        jLabel32.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel32.setText("Certificados:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, -1, 40));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 70, 10));

        cbxEspecializacion.setBackground(new java.awt.Color(204, 204, 204));
        cbxEspecializacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Matematica", "Comunicacion", "Historia", "Desarrolllo Personal", "Ciencias", "Computacion" }));
        cbxEspecializacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEspecializacionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEspecializacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 190, 30));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/file-chart.png"))); // NOI18N
        jButton3.setText("Seleccionar Archivo");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, 180, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/file-chart.png"))); // NOI18N
        jButton4.setText("Seleccionar Archivo");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 170, 30));

        txtFecha.setBackground(new java.awt.Color(204, 204, 204));
        txtFecha.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 210, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AgruparBotones(){
        groupSex=new ButtonGroup();
        groupSex.add(rdbMas);
        groupSex.add(rdbFem);
    }
    
    private void rdbFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFemActionPerformed

    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void cbxDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDocActionPerformed

    private void txtDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocActionPerformed

    private void cbxAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAcademicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAcademicoActionPerformed

    private void cbxDispHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDispHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDispHorariaActionPerformed

    private void cbxEspecializacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspecializacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEspecializacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JComboBox<String> cbxAcademico;
    public javax.swing.JComboBox<String> cbxDispHoraria;
    public javax.swing.JComboBox<String> cbxDoc;
    public javax.swing.JComboBox<String> cbxEspecializacion;
    public javax.swing.JComboBox<String> cbxPais;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JRadioButton rdbFem;
    public javax.swing.JRadioButton rdbMas;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtAñosExperiencia;
    public javax.swing.JTextField txtContacto;
    public javax.swing.JTextField txtDoc;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtInstiAnteriores;
    public javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
