/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author cr075
 */
public class FrmContrasena extends javax.swing.JFrame {

    /**
     * Creates new form FrmContraseña
     */
    public FrmContrasena() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        txtNuevaContr = new javax.swing.JTextField();
        btnCambiarcontr = new javax.swing.JButton();
        txtRepCont = new javax.swing.JTextField();
        btnIralInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/password.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, 70));

        txtUsu.setFont(new java.awt.Font("Swis721 Ex BT", 1, 12)); // NOI18N
        txtUsu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Swis721 Ex BT", 1, 12))); // NOI18N
        jPanel1.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 230, 50));

        txtNuevaContr.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Nueva Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Swis721 Ex BT", 1, 12))); // NOI18N
        jPanel1.add(txtNuevaContr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 230, 50));

        btnCambiarcontr.setBackground(new java.awt.Color(51, 102, 255));
        btnCambiarcontr.setFont(new java.awt.Font("Swis721 Ex BT", 1, 12)); // NOI18N
        btnCambiarcontr.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarcontr.setText("CAMBIAR CONTRASEÑA");
        btnCambiarcontr.setBorder(null);
        btnCambiarcontr.setOpaque(true);
        jPanel1.add(btnCambiarcontr, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 40));

        txtRepCont.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repetir Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Swis721 Ex BT", 1, 12))); // NOI18N
        jPanel1.add(txtRepCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 230, 50));

        btnIralInicio.setBackground(new java.awt.Color(204, 204, 255));
        btnIralInicio.setFont(new java.awt.Font("Swis721 Ex BT", 1, 12)); // NOI18N
        btnIralInicio.setText("IR AL INICIO");
        btnIralInicio.setBorder(null);
        btnIralInicio.setOpaque(true);
        jPanel1.add(btnIralInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 380, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCambiarcontr;
    public javax.swing.JButton btnIralInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtNuevaContr;
    public javax.swing.JTextField txtRepCont;
    public javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
