/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author cr075
 */
public class RgtSalon extends javax.swing.JInternalFrame {

    /**
     * Creates new form RgtEstudiante
     */
    public RgtSalon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxUbi = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cbxNom = new javax.swing.JComboBox<>();
        txtCapa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        cbxSeccion = new javax.swing.JComboBox<>();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(670, 416));
        jPanel1.setPreferredSize(new java.awt.Dimension(670, 416));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Salón");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 430, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 670, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Información General del Salón");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 180, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 410, 10));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel4.setText("Nombre del salón:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, 40));

        btnGuardar.setBackground(new java.awt.Color(51, 102, 255));
        btnGuardar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("REGISTRAR");
        btnGuardar.setBorder(null);
        btnGuardar.setOpaque(true);
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setOpaque(true);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Código:*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));

        txtCod.setBackground(new java.awt.Color(204, 204, 204));
        txtCod.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCod.setBorder(null);
        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 30));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Capacidad:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 40));

        cbxUbi.setBackground(new java.awt.Color(204, 204, 204));
        cbxUbi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Piso A1", "Piso A2", "Piso B1", "Piso B2" }));
        cbxUbi.setBorder(null);
        cbxUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUbiActionPerformed(evt);
            }
        });
        jPanel1.add(cbxUbi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 110, 30));

        jLabel15.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel15.setText("Ubicación:*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 40));

        cbxNom.setBackground(new java.awt.Color(204, 204, 204));
        cbxNom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Grado 1°", "Grado 2°", "Grado 3°", "Grado 4°", "Grado 5°", "Grado 6°", "Laboratorio de Química", "Laboratorio de Física", "Computación", "Sala Proyector" }));
        cbxNom.setBorder(null);
        cbxNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomActionPerformed(evt);
            }
        });
        jPanel1.add(cbxNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 190, 30));

        txtCapa.setBackground(new java.awt.Color(204, 204, 204));
        txtCapa.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCapa.setBorder(null);
        txtCapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 120, 30));

        jLabel13.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel13.setText("Estado:* ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 40));

        jLabel6.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel6.setText("Sección:*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 40));

        cbxEstado.setBackground(new java.awt.Color(204, 204, 204));
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Activo", "Inactivo" }));
        cbxEstado.setBorder(null);
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 90, 30));

        cbxSeccion.setBackground(new java.awt.Color(204, 204, 204));
        cbxSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A", "B" }));
        cbxSeccion.setBorder(null);
        cbxSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 416));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUbiActionPerformed

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodActionPerformed

    private void cbxNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNomActionPerformed

    private void txtCapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapaActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void cbxSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSeccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JComboBox<String> cbxEstado;
    public javax.swing.JComboBox<String> cbxNom;
    public javax.swing.JComboBox<String> cbxSeccion;
    public javax.swing.JComboBox<String> cbxUbi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextField txtCapa;
    public javax.swing.JTextField txtCod;
    // End of variables declaration//GEN-END:variables
}
