/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.ButtonGroup;

/**
 *
 * @author cr075
 */
public class EdtAlumno extends javax.swing.JInternalFrame {

   public ButtonGroup grupoSexo,grupoDisc,grupoOtro;
   
    public EdtAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cbxTipoDoc = new javax.swing.JComboBox<>();
        txtNumDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        cbxDpto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        cbxPais = new javax.swing.JComboBox<>();
        cbxLengua = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rbtnFem = new javax.swing.JRadioButton();
        rbtnMas = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        cbxDist = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        rbtnDisNo = new javax.swing.JRadioButton();
        rbtnDisSi = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rbtnOtroNo = new javax.swing.JRadioButton();
        rbtnOtroSi = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar Alumno");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 390, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 850, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Información General del Estudiante");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 560, 10));

        cbxTipoDoc.setBackground(new java.awt.Color(204, 204, 204));
        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dni", "Pasaporte" }));
        cbxTipoDoc.setBorder(null);
        cbxTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoDocActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, 30));

        txtNumDoc.setBackground(new java.awt.Color(204, 204, 204));
        txtNumDoc.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNumDoc.setBorder(null);
        txtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 240, 30));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel4.setText("N° de Documento:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 40));

        btnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(null);
        btnActualizar.setOpaque(true);
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setOpaque(true);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de Documento:*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 40));

        txtNom.setBackground(new java.awt.Color(204, 204, 204));
        txtNom.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNom.setBorder(null);
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 220, 30));

        jLabel6.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel6.setText("Tiene Discapacidad?*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 40));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Nombres:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 40));

        txtApellidos.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidos.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtApellidos.setBorder(null);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 280, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 70, 10));

        jLabel8.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel8.setText("Datos de Nacimiento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 630, 10));

        cbxDpto.setBackground(new java.awt.Color(204, 204, 204));
        cbxDpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Callao (Provincia Constitucional)", "Lima", "Otro" }));
        cbxDpto.setBorder(null);
        cbxDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDptoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 170, 30));

        jLabel9.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel9.setText("Departamento:*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 120, 40));

        jLabel10.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel10.setText("Lengua Materna:*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, 40));

        jLabel11.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel11.setText("Fecha:* ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, 40));

        txtFecha.setBackground(new java.awt.Color(204, 204, 204));
        txtFecha.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 170, 30));

        cbxPais.setBackground(new java.awt.Color(204, 204, 204));
        cbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Peru", "Otro" }));
        cbxPais.setBorder(null);
        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 150, 30));

        cbxLengua.setBackground(new java.awt.Color(204, 204, 204));
        cbxLengua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Español", "Quechua", "Aymara", "Otro" }));
        cbxLengua.setBorder(null);
        cbxLengua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLenguaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxLengua, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 180, 30));

        jLabel14.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel14.setText("Distrito:* ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 40));

        jLabel15.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel15.setText("Apellidos:*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, 40));

        rbtnFem.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnFem.setText("Femenino");
        rbtnFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        rbtnMas.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnMas.setText("Masculino");
        jPanel1.add(rbtnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel20.setText("País:*");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 70, 10));

        jLabel21.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel21.setText("Datos de Contacto");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 120, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 660, 10));

        cbxDist.setBackground(new java.awt.Color(204, 204, 204));
        cbxDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Comas", "Puente Piedra", "Rímac", "San Martín de Porres", "Lima (Centro)", "Otro" }));
        cbxDist.setBorder(null);
        cbxDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDistActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 180, 30));

        jLabel12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel12.setText("Sexo:*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 40));

        rbtnDisNo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnDisNo.setText("No");
        rbtnDisNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDisNoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnDisNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        rbtnDisSi.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnDisSi.setText("Si");
        jPanel1.add(rbtnDisSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel16.setText("Tiene otras condiciones?*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, 20));

        rbtnOtroNo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnOtroNo.setText("No");
        rbtnOtroNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOtroNoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnOtroNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, -1, -1));

        rbtnOtroSi.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnOtroSi.setText("Si");
        jPanel1.add(rbtnOtroSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, -1, -1));

        jLabel25.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel25.setText("Correo o N° Contacto:*");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, 40));

        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 850, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemActionPerformed

    private void cbxLenguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLenguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLenguaActionPerformed

    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisActionPerformed

    private void cbxDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDptoActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void cbxTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoDocActionPerformed

    private void cbxDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDistActionPerformed

    private void rbtnDisNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDisNoActionPerformed

    private void rbtnOtroNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOtroNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnOtroNoActionPerformed

    private void txtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocActionPerformed
    public void AgruparBotones(){
        grupoSexo=new ButtonGroup();
        grupoSexo.add(rbtnFem);
        grupoSexo.add(rbtnMas);
        grupoDisc=new ButtonGroup();
         grupoDisc.add(rbtnDisSi);
         grupoDisc.add(rbtnDisNo);
        grupoOtro=new ButtonGroup();
        grupoOtro.add(rbtnOtroSi);
        grupoOtro.add(rbtnOtroNo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JComboBox<String> cbxDist;
    public javax.swing.JComboBox<String> cbxDpto;
    public javax.swing.JComboBox<String> cbxLengua;
    public javax.swing.JComboBox<String> cbxPais;
    public javax.swing.JComboBox<String> cbxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JRadioButton rbtnDisNo;
    public javax.swing.JRadioButton rbtnDisSi;
    public javax.swing.JRadioButton rbtnFem;
    public javax.swing.JRadioButton rbtnMas;
    public javax.swing.JRadioButton rbtnOtroNo;
    public javax.swing.JRadioButton rbtnOtroSi;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtNom;
    public javax.swing.JTextField txtNumDoc;
    // End of variables declaration//GEN-END:variables
}
