/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import java.awt.Color;
import javax.swing.ButtonGroup;

/**
 *
 * @author cr075
 */
public class EdtMatricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form RgtEstudiante
     */   public ButtonGroup grupoSexo,grupoDisc,grupoOtro;

    public EdtMatricula() {
        initComponents();
        // Inicialmente, el botón no tiene color, así que le asignas un color base
        
        togTraslado.setBackground(Color.DARK_GRAY);
        togAntiguo.setBackground(Color.DARK_GRAY);
        togNuevo.setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rbtnFem = new javax.swing.JRadioButton();
        rbtnMas = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rbtnDisNo = new javax.swing.JRadioButton();
        rbtnDisSi = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rbtnOtroNo = new javax.swing.JRadioButton();
        rbtnOtroSi = new javax.swing.JRadioButton();
        jSeparator5 = new javax.swing.JSeparator();
        panelTras = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField12 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        togTraslado = new javax.swing.JToggleButton();
        jLabel27 = new javax.swing.JLabel();
        txtColePre = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        panelAnti = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        togAntiguo = new javax.swing.JToggleButton();
        panelNue = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        togNuevo = new javax.swing.JToggleButton();
        cbxSeccion = new javax.swing.JComboBox<>();
        cbxGrado = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtFechaMat = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cbxTipoDoc = new javax.swing.JComboBox<>();
        txtNumDoc = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        cbxPais = new javax.swing.JComboBox<>();
        cbxDpto = new javax.swing.JComboBox<>();
        cbxDist = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JTextField();
        cbxLengua = new javax.swing.JComboBox<>();
        txtCorreo = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        btn_referido = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Editar Matrícula ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 610, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 850, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Información General del Estudiante");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 560, 10));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel4.setText("N° de Documento:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, 40));

        btnActualizar.setBackground(new java.awt.Color(51, 102, 255));
        btnActualizar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setBorder(null);
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de Documento:*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));

        jLabel6.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel6.setText("Tiene Discapacidad?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, 40));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Nombres:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 70, 10));

        jLabel8.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel8.setText("Datos de Nacimiento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 630, 10));

        jLabel9.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel9.setText("Departamento:*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 120, 40));

        jLabel10.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel10.setText("Lengua Materna:*");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, 40));

        jLabel11.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel11.setText("Fecha:* ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 40));

        jLabel14.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel14.setText("Distrito:* ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));

        jLabel15.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel15.setText("Apellidos:*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, 40));

        rbtnFem.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnFem.setText("Femenino");
        rbtnFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        rbtnMas.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnMas.setText("Masculino");
        jPanel1.add(rbtnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel20.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel20.setText("País:*");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 70, 10));

        jLabel21.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel21.setText("Datos de Contacto");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 120, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 660, 10));

        jLabel22.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel22.setText("Sección: ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 40));

        jLabel12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel12.setText("Sexo:*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, 40));

        rbtnDisNo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnDisNo.setText("No");
        rbtnDisNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDisNoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnDisNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        rbtnDisSi.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnDisSi.setText("Si");
        jPanel1.add(rbtnDisSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        jLabel16.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel16.setText("Tiene otras condiciones?");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, 20));

        rbtnOtroNo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnOtroNo.setText("No");
        rbtnOtroNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOtroNoActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnOtroNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, -1));

        rbtnOtroSi.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnOtroSi.setText("Si");
        jPanel1.add(rbtnOtroSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 860, -1));

        panelTras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Es de Traslado? ");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jToggleButton2.setText("SI");
        jPanel4.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        jTextField12.setBackground(new java.awt.Color(204, 204, 204));
        jTextField12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jTextField12.setBorder(null);
        jPanel4.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 140, 30));

        jLabel26.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel26.setText("Colegio Procedente: ");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 40));

        panelTras.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 300, 120));

        jLabel19.setText("Es de Traslado? ");
        panelTras.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        togTraslado.setText("NO        |");
        togTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togTrasladoActionPerformed(evt);
            }
        });
        panelTras.add(togTraslado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        jLabel27.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel27.setText("Colegio Precedente: ");
        panelTras.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 40));

        txtColePre.setBackground(new java.awt.Color(204, 204, 204));
        txtColePre.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtColePre.setBorder(null);
        panelTras.add(txtColePre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 30));

        jPanel1.add(panelTras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 290, 110));

        jLabel25.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel25.setText("Correo o N° Contacto: ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, 40));

        panelAnti.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setText("Es alumno antiguo? ");
        panelAnti.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        togAntiguo.setText(" NO        |");
        togAntiguo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togAntiguoActionPerformed(evt);
            }
        });
        panelAnti.add(togAntiguo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 90, 30));

        jPanel1.add(panelAnti, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 350, 60));

        panelNue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setText("Es alumno nuevo? ");
        panelNue.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        togNuevo.setText("NO      |");
        togNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togNuevoActionPerformed(evt);
            }
        });
        panelNue.add(togNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 80, 30));

        jPanel1.add(panelNue, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, 220, 60));

        cbxSeccion.setBackground(new java.awt.Color(204, 204, 204));
        cbxSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        cbxSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSeccionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 110, 30));

        cbxGrado.setBackground(new java.awt.Color(204, 204, 204));
        cbxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grado 1°", "Grado 2°", "Grado 3°", "Grado 4°", "Grado 5°", "Grado 6°" }));
        cbxGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGradoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxGrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 120, 30));

        jLabel24.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel24.setText("a matricular: ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, -1, 20));

        jLabel29.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel29.setText("Grado ");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, 20));

        txtFechaMat.setBackground(new java.awt.Color(204, 204, 204));
        txtFechaMat.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtFechaMat.setBorder(null);
        jPanel1.add(txtFechaMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, 170, 30));

        jLabel32.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel32.setText("Código de Matrícula:* ");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 150, 40));

        txtCod.setBackground(new java.awt.Color(204, 204, 204));
        txtCod.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCod.setBorder(null);
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, 170, 30));

        jLabel33.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel33.setText("Fecha:* ");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, 40));

        cbxTipoDoc.setBackground(new java.awt.Color(204, 204, 204));
        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dni", "Pasaporte" }));
        cbxTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoDocActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 220, 30));

        txtNumDoc.setBackground(new java.awt.Color(204, 204, 204));
        txtNumDoc.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNumDoc.setBorder(null);
        txtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 210, 30));

        txtApellidos.setBackground(new java.awt.Color(204, 204, 204));
        txtApellidos.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtApellidos.setBorder(null);
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 230, 30));

        cbxPais.setBackground(new java.awt.Color(204, 204, 204));
        cbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Peru", "Otro" }));
        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 150, 30));

        cbxDpto.setBackground(new java.awt.Color(204, 204, 204));
        cbxDpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Callao (Provincia Constitucional)", "Lima", "Otro" }));
        cbxDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDptoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 170, 30));

        cbxDist.setBackground(new java.awt.Color(204, 204, 204));
        cbxDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Comas", "Puente Piedra", "Rímac", "San Martín de Porres", "Lima (Centro)", "Otro" }));
        cbxDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDistActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDist, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 180, 30));

        txtFecha.setBackground(new java.awt.Color(204, 204, 204));
        txtFecha.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 170, 30));

        cbxLengua.setBackground(new java.awt.Color(204, 204, 204));
        cbxLengua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Español", "Quechua", "Aymara", "Otro" }));
        cbxLengua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLenguaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxLengua, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 180, 30));

        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 230, 30));

        txtNom.setBackground(new java.awt.Color(204, 204, 204));
        txtNom.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNom.setBorder(null);
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 220, 30));

        btn_referido.setText("Asignar o cambiar Referidor");
        btn_referido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_referidoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_referido, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 180, 30));

        jLabel13.setText("Referido : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 850, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemActionPerformed

    private void cbxGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGradoActionPerformed

    private void rbtnDisNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDisNoActionPerformed

    private void rbtnOtroNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOtroNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnOtroNoActionPerformed

    private void cbxSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSeccionActionPerformed

    private void togTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togTrasladoActionPerformed
      
        if (togTraslado.isSelected()) { 
            togTraslado.setText("|  SI");
            togTraslado.setBackground(Color.cyan);
            togTraslado.setVisible(true);
             // Hacer los otros paneles invisibles
            panelAnti.setVisible(false);
            panelNue.setVisible(false);
        } else {
            togTraslado.setText("NO  |");
            togTraslado.setBackground(Color.DARK_GRAY);
            togTraslado.setVisible(true);
            panelTras.setVisible(false);
            panelAnti.setVisible(true);
            panelNue.setVisible(true);
         }
         togTraslado.repaint(); 
         
    }//GEN-LAST:event_togTrasladoActionPerformed

    private void togAntiguoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togAntiguoActionPerformed
       if (togAntiguo.isSelected()) {
            togAntiguo.setText("|  SI");
            togAntiguo.setBackground(Color.cyan);
            togAntiguo.setVisible(true);
             // Hacer los otros paneles invisibles
            panelTras.setVisible(false);
            panelNue.setVisible(false);
        } else {
            togAntiguo.setText("NO  |");
            togAntiguo.setBackground(Color.DARK_GRAY);
            togAntiguo.setVisible(true);
            panelAnti.setVisible(false);
            panelTras.setVisible(true);
            panelNue.setVisible(true);
       }
            togAntiguo.repaint(); 
    }//GEN-LAST:event_togAntiguoActionPerformed

    private void togNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togNuevoActionPerformed
         if (togNuevo.isSelected()) {
            togNuevo.setText("|  SI");
            togNuevo.setBackground(Color.cyan);
            togNuevo.setVisible(true);
             // Hacer los otros paneles invisibles
            panelTras.setVisible(false);
            panelAnti.setVisible(false);
        } else {
            togNuevo.setText("NO  |");
            togNuevo.setBackground(Color.DARK_GRAY);
            togNuevo.setVisible(true); 
             panelNue.setVisible(false);
            panelTras.setVisible(true);
            panelAnti.setVisible(true);
         }
            togNuevo.repaint(); 
    }//GEN-LAST:event_togNuevoActionPerformed

    private void cbxTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoDocActionPerformed

    private void txtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocActionPerformed

    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisActionPerformed

    private void cbxDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDptoActionPerformed

    private void cbxDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDistActionPerformed

    private void cbxLenguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLenguaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxLenguaActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void btn_referidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_referidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_referidoActionPerformed

public void AgruparBotones(){
        grupoSexo=new ButtonGroup();
        grupoSexo.add(rbtnFem);
        grupoSexo.add(rbtnMas);
        grupoDisc=new ButtonGroup();
         grupoDisc.add(rbtnDisSi);
         grupoDisc.add(rbtnDisNo);
        grupoOtro=new ButtonGroup();
        grupoOtro.add(rbtnOtroSi);
        grupoOtro.add(rbtnOtroNo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JToggleButton btn_referido;
    public javax.swing.JComboBox<String> cbxDist;
    public javax.swing.JComboBox<String> cbxDpto;
    public javax.swing.JComboBox<String> cbxGrado;
    public javax.swing.JComboBox<String> cbxLengua;
    public javax.swing.JComboBox<String> cbxPais;
    public javax.swing.JComboBox<String> cbxSeccion;
    public javax.swing.JComboBox<String> cbxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JToggleButton jToggleButton2;
    public javax.swing.JPanel panelAnti;
    public javax.swing.JPanel panelNue;
    public javax.swing.JPanel panelTras;
    public javax.swing.JRadioButton rbtnDisNo;
    public javax.swing.JRadioButton rbtnDisSi;
    public javax.swing.JRadioButton rbtnFem;
    public javax.swing.JRadioButton rbtnMas;
    public javax.swing.JRadioButton rbtnOtroNo;
    public javax.swing.JRadioButton rbtnOtroSi;
    public javax.swing.JToggleButton togAntiguo;
    public javax.swing.JToggleButton togNuevo;
    public javax.swing.JToggleButton togTraslado;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtCod;
    public javax.swing.JTextField txtColePre;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtFechaMat;
    public javax.swing.JTextField txtNom;
    public javax.swing.JTextField txtNumDoc;
    // End of variables declaration//GEN-END:variables
}
