/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author cr075
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        dspEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        itemRgtAlumno = new javax.swing.JMenuItem();
        itemRgtApoderado = new javax.swing.JMenuItem();
        itemRgtProfesor = new javax.swing.JMenuItem();
        itemRgtSalon = new javax.swing.JMenuItem();
        itemRgtCursos = new javax.swing.JMenuItem();
        itemRgtHorario = new javax.swing.JMenuItem();
        itemElgrSinMatAlumno = new javax.swing.JMenuItem();
        itemRgtMatricula = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        LstAlumMatr = new javax.swing.JMenuItem();
        itemCursosProfesor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        itemRptAlumno = new javax.swing.JMenuItem();
        itemEdtAlumno = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        itemRptApoderado = new javax.swing.JMenuItem();
        itemEdtApoderado = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        itemRptProfesor = new javax.swing.JMenuItem();
        itemEdtProfesor = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        itemRptSalon = new javax.swing.JMenuItem();
        itemEdtSalon = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        itemRptCurso = new javax.swing.JMenuItem();
        itemEdtCurso = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        itemRptHorario = new javax.swing.JMenuItem();
        itemEdtHorario = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        itemRptMatricula = new javax.swing.JMenuItem();
        itemEdtMatricula = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem5.setText("jMenuItem5");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dspEscritorio.setBackground(new java.awt.Color(102, 204, 255));
        dspEscritorio.setPreferredSize(new java.awt.Dimension(2000, 900));

        javax.swing.GroupLayout dspEscritorioLayout = new javax.swing.GroupLayout(dspEscritorio);
        dspEscritorio.setLayout(dspEscritorioLayout);
        dspEscritorioLayout.setHorizontalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2000, Short.MAX_VALUE)
        );
        dspEscritorioLayout.setVerticalGroup(
            dspEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        getContentPane().add(dspEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2000, 900));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu1.setText("Menú");
        jMenu1.setFont(new java.awt.Font("Swis721 Ex BT", 1, 12)); // NOI18N

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/registro (1).png"))); // NOI18N
        jMenu4.setText("Registrar");
        jMenu4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRgtAlumno.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRgtAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/alumno.png"))); // NOI18N
        itemRgtAlumno.setText("Alumno");
        itemRgtAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRgtAlumnoActionPerformed(evt);
            }
        });
        jMenu4.add(itemRgtAlumno);

        itemRgtApoderado.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRgtApoderado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/padre-e-hijo.png"))); // NOI18N
        itemRgtApoderado.setText("Apoderado");
        jMenu4.add(itemRgtApoderado);

        itemRgtProfesor.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRgtProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/profesor.png"))); // NOI18N
        itemRgtProfesor.setText("Profesor");
        jMenu4.add(itemRgtProfesor);

        itemRgtSalon.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRgtSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/peluqueria.png"))); // NOI18N
        itemRgtSalon.setText("Salón");
        jMenu4.add(itemRgtSalon);

        itemRgtCursos.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRgtCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/biblioteca (1).png"))); // NOI18N
        itemRgtCursos.setText("Cursos");
        jMenu4.add(itemRgtCursos);

        itemRgtHorario.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRgtHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/calendario (2).png"))); // NOI18N
        itemRgtHorario.setText("Horario");
        jMenu4.add(itemRgtHorario);

        itemElgrSinMatAlumno.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemElgrSinMatAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/portapapeles.png"))); // NOI18N
        itemElgrSinMatAlumno.setText("Elegir Alumno Sin Matrícula");
        itemElgrSinMatAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemElgrSinMatAlumnoActionPerformed(evt);
            }
        });
        jMenu4.add(itemElgrSinMatAlumno);

        itemRgtMatricula.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRgtMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/tesis.png"))); // NOI18N
        itemRgtMatricula.setText("Matrícula");
        jMenu4.add(itemRgtMatricula);

        jMenu1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/lista-de-verificacion.png"))); // NOI18N
        jMenu6.setText("Listas");
        jMenu6.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        LstAlumMatr.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        LstAlumMatr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/filtrar (1).png"))); // NOI18N
        LstAlumMatr.setText("Alumnos Matriculados");
        jMenu6.add(LstAlumMatr);

        itemCursosProfesor.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemCursosProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/filtrar (1).png"))); // NOI18N
        itemCursosProfesor.setText("Cursos de Docente");
        jMenu6.add(itemCursosProfesor);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reportes");
        jMenu2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 12)); // NOI18N

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/reporte-de-negocios.png"))); // NOI18N
        jMenu7.setText("Alumno");
        jMenu7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRptAlumno.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRptAlumno.setText("Reporte");
        jMenu7.add(itemRptAlumno);

        itemEdtAlumno.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemEdtAlumno.setText("Actualizar");
        jMenu7.add(itemEdtAlumno);

        jMenu2.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/reporte-de-negocios.png"))); // NOI18N
        jMenu8.setText("Apoderado");
        jMenu8.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRptApoderado.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRptApoderado.setText("Reporte");
        jMenu8.add(itemRptApoderado);

        itemEdtApoderado.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemEdtApoderado.setText("Actualización");
        jMenu8.add(itemEdtApoderado);

        jMenu2.add(jMenu8);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/reporte-de-negocios.png"))); // NOI18N
        jMenu11.setText("Profesor");
        jMenu11.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRptProfesor.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRptProfesor.setText("Reporte");
        jMenu11.add(itemRptProfesor);

        itemEdtProfesor.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemEdtProfesor.setText("Actualización");
        jMenu11.add(itemEdtProfesor);

        jMenu2.add(jMenu11);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/reporte-de-negocios.png"))); // NOI18N
        jMenu10.setText("Salón");
        jMenu10.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRptSalon.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRptSalon.setText("Reporte");
        jMenu10.add(itemRptSalon);

        itemEdtSalon.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemEdtSalon.setText("Actualización");
        jMenu10.add(itemEdtSalon);

        jMenu2.add(jMenu10);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/reporte-de-negocios.png"))); // NOI18N
        jMenu9.setText("Curso");
        jMenu9.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRptCurso.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRptCurso.setText("Reporte");
        jMenu9.add(itemRptCurso);

        itemEdtCurso.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemEdtCurso.setText("Actualización");
        jMenu9.add(itemEdtCurso);

        jMenu2.add(jMenu9);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/reporte-de-negocios.png"))); // NOI18N
        jMenu12.setText("Horario");
        jMenu12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRptHorario.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRptHorario.setText("Reporte");
        jMenu12.add(itemRptHorario);

        itemEdtHorario.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemEdtHorario.setText("Actualización");
        jMenu12.add(itemEdtHorario);

        jMenu2.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/reporte-de-negocios.png"))); // NOI18N
        jMenu13.setText("Matrícula");
        jMenu13.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N

        itemRptMatricula.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemRptMatricula.setText("Reporte");
        jMenu13.add(itemRptMatricula);

        itemEdtMatricula.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        itemEdtMatricula.setText("Actualización");
        jMenu13.add(itemEdtMatricula);

        jMenu2.add(jMenu13);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemElgrSinMatAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemElgrSinMatAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemElgrSinMatAlumnoActionPerformed

    private void itemRgtAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRgtAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRgtAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem LstAlumMatr;
    public javax.swing.JDesktopPane dspEscritorio;
    public javax.swing.JMenuItem itemCursosProfesor;
    public javax.swing.JMenuItem itemEdtAlumno;
    public javax.swing.JMenuItem itemEdtApoderado;
    public javax.swing.JMenuItem itemEdtCurso;
    public javax.swing.JMenuItem itemEdtHorario;
    public javax.swing.JMenuItem itemEdtMatricula;
    public javax.swing.JMenuItem itemEdtProfesor;
    public javax.swing.JMenuItem itemEdtSalon;
    public javax.swing.JMenuItem itemElgrSinMatAlumno;
    public javax.swing.JMenuItem itemRgtAlumno;
    public javax.swing.JMenuItem itemRgtApoderado;
    public javax.swing.JMenuItem itemRgtCursos;
    public javax.swing.JMenuItem itemRgtHorario;
    public javax.swing.JMenuItem itemRgtMatricula;
    public javax.swing.JMenuItem itemRgtProfesor;
    public javax.swing.JMenuItem itemRgtSalon;
    public javax.swing.JMenuItem itemRptAlumno;
    public javax.swing.JMenuItem itemRptApoderado;
    public javax.swing.JMenuItem itemRptCurso;
    public javax.swing.JMenuItem itemRptHorario;
    public javax.swing.JMenuItem itemRptMatricula;
    public javax.swing.JMenuItem itemRptProfesor;
    public javax.swing.JMenuItem itemRptSalon;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
