/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author cr075
 */
public class RgtApoderado extends javax.swing.JInternalFrame {

    /**
     * Creates new form RgtEstudiante
     */
    public RgtApoderado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cbxRelacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApe = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        txtCelu = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtNdocA = new javax.swing.JTextField();
        cbxTipoDoc = new javax.swing.JComboBox<>();
        cbxPais = new javax.swing.JComboBox<>();
        cbxDpto = new javax.swing.JComboBox<>();
        cbxDist = new javax.swing.JComboBox<>();
        txtNumDoc = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(872, 596));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 110));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Apoderado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 480, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 850, 110));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Información General del Apoderado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 560, 10));

        cbxRelacion.setBackground(new java.awt.Color(204, 204, 204));
        cbxRelacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Padre", "Madre", "Otro Parentesco" }));
        cbxRelacion.setBorder(null);
        cbxRelacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRelacionActionPerformed(evt);
            }
        });
        jPanel1.add(cbxRelacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 30));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel4.setText("N° de Documento:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 40));

        btnAgregar.setBackground(new java.awt.Color(51, 102, 255));
        btnAgregar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("REGISTRAR");
        btnAgregar.setBorder(null);
        btnAgregar.setOpaque(true);
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setOpaque(true);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de Documento:*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, 40));

        txtNom.setBackground(new java.awt.Color(204, 204, 204));
        txtNom.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNom.setBorder(null);
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        jPanel1.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 250, 30));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Nombres:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, 40));

        txtApe.setBackground(new java.awt.Color(204, 204, 204));
        txtApe.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtApe.setBorder(null);
        jPanel1.add(txtApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 280, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, 10));

        jLabel8.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel8.setText("Datos de Nacimiento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 210, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 630, 10));

        jLabel9.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel9.setText("Departamento:*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 120, 40));

        jLabel15.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel15.setText("Apellidos:*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 40));

        jLabel20.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel20.setText("País:*");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 70, 10));

        jLabel21.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel21.setText("Datos de Contacto");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 120, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 660, 10));

        jLabel22.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel22.setText("N° Celular: ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, 40));

        txtCelu.setBackground(new java.awt.Color(204, 204, 204));
        txtCelu.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCelu.setBorder(null);
        jPanel1.add(txtCelu, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 170, 30));

        jLabel24.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel24.setText("Correo: ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 40));

        txtCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 170, 30));

        jLabel12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel12.setText("Relación con el estudiante: ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));

        jLabel17.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel17.setText("Distrito:* ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, 40));

        jLabel25.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel25.setText("N° Doc. del Alumno: ");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 40));

        txtNdocA.setBackground(new java.awt.Color(204, 204, 204));
        txtNdocA.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNdocA.setBorder(null);
        jPanel1.add(txtNdocA, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 180, 30));

        cbxTipoDoc.setBackground(new java.awt.Color(204, 204, 204));
        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dni", "Pasaporte" }));
        cbxTipoDoc.setBorder(null);
        cbxTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoDocActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 190, 30));

        cbxPais.setBackground(new java.awt.Color(204, 204, 204));
        cbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Peru", "Otro" }));
        cbxPais.setBorder(null);
        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 150, 30));

        cbxDpto.setBackground(new java.awt.Color(204, 204, 204));
        cbxDpto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione ", "Callao (Provincia Constitucional)", "Lima", "Otro" }));
        cbxDpto.setBorder(null);
        cbxDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDptoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 170, 30));

        cbxDist.setBackground(new java.awt.Color(204, 204, 204));
        cbxDist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Comas", "Puente Piedra", "Rímac", "San Martín de Porres", "Lima (Centro)", "Otro" }));
        cbxDist.setBorder(null);
        cbxDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDistActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDist, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 180, 30));

        txtNumDoc.setBackground(new java.awt.Color(204, 204, 204));
        txtNumDoc.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNumDoc.setBorder(null);
        txtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 190, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 850, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void cbxRelacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRelacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRelacionActionPerformed

    private void cbxTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoDocActionPerformed

    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisActionPerformed

    private void cbxDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDptoActionPerformed

    private void cbxDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDistActionPerformed

    private void txtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JComboBox<String> cbxDist;
    public javax.swing.JComboBox<String> cbxDpto;
    public javax.swing.JComboBox<String> cbxPais;
    public javax.swing.JComboBox<String> cbxRelacion;
    public javax.swing.JComboBox<String> cbxTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    public javax.swing.JTextField txtApe;
    public javax.swing.JTextField txtCelu;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNdocA;
    public javax.swing.JTextField txtNom;
    public javax.swing.JTextField txtNumDoc;
    // End of variables declaration//GEN-END:variables
}
