/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import javax.swing.ButtonGroup;

/**
 *
 * @author cr075
 */
public class RgtProfesor extends javax.swing.JInternalFrame {
    public ButtonGroup groupSex;
    
    /**
     * Creates new form RgtEstudiante
     */
    public RgtProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cbxTipoDoc = new javax.swing.JComboBox<>();
        txtNumDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cbxPais = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        rbtnFem = new javax.swing.JRadioButton();
        rbtnMas = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtAñosExperiencia = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        cbxGrupoAcademico = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbxDispHoraria = new javax.swing.JComboBox<>();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtInstiAnterior = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        cbxEspecialización = new javax.swing.JComboBox<>();
        btn_certificados = new javax.swing.JButton();
        btn_curriculum = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        check_certificado = new javax.swing.JCheckBox();
        check_curriculum = new javax.swing.JCheckBox();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 90));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar Profesor");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 430, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 860, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel3.setText("Información General del Profesor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 560, 10));

        cbxTipoDoc.setBackground(new java.awt.Color(204, 204, 204));
        cbxTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dni", "Pasaporte" }));
        cbxTipoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoDocActionPerformed(evt);
            }
        });
        jPanel1.add(cbxTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 200, 30));

        txtNumDoc.setBackground(new java.awt.Color(204, 204, 204));
        txtNumDoc.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNumDoc.setBorder(null);
        txtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 240, 30));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel4.setText("N° de Documento:*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 40));

        btnRegistrar.setBackground(new java.awt.Color(51, 102, 255));
        btnRegistrar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setBorder(null);
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 650, 110, 40));

        btnCancelar.setBackground(new java.awt.Color(102, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 650, 110, 40));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel5.setText("Tipo de Documento:*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 40));

        txtNombres.setBackground(new java.awt.Color(204, 204, 204));
        txtNombres.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 260, 30));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel7.setText("Nombres:*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 40));

        txtApellido.setBackground(new java.awt.Color(204, 204, 204));
        txtApellido.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtApellido.setBorder(null);
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 280, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, 10));

        jLabel8.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel8.setText("Datos de Nacimiento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 210, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 630, 10));

        jLabel11.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel11.setText("Fecha:* ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, 40));

        cbxPais.setBackground(new java.awt.Color(204, 204, 204));
        cbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Peru", "Otro" }));
        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        jPanel1.add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 190, 30));

        jLabel15.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel15.setText("Apellidos:*");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 40));

        rbtnFem.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnFem.setText("Femenino");
        rbtnFem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        rbtnMas.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        rbtnMas.setText("Masculino");
        jPanel1.add(rbtnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel20.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel20.setText("País:*");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 40));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 70, 10));

        jLabel21.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel21.setText("Datos de Contacto");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 120, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 660, 10));

        txtAñosExperiencia.setBackground(new java.awt.Color(204, 204, 204));
        txtAñosExperiencia.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtAñosExperiencia.setBorder(null);
        jPanel1.add(txtAñosExperiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 70, 30));

        jLabel24.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel24.setText("Correo o N° Contacto:* ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 40));

        txtContacto.setBackground(new java.awt.Color(204, 204, 204));
        txtContacto.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtContacto.setBorder(null);
        jPanel1.add(txtContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 240, 30));

        jLabel12.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel12.setText("Sexo:*");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 70, 10));

        jLabel17.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel17.setText("Formación Academica");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 210, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 630, 10));

        cbxGrupoAcademico.setBackground(new java.awt.Color(204, 204, 204));
        cbxGrupoAcademico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1 Grado", "2 Grado", "3 Grado", "4 Grado", "5 Grado" }));
        cbxGrupoAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGrupoAcademicoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxGrupoAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 170, 30));

        jLabel18.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel18.setText("Grado Académico:* ");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 150, 40));

        jLabel19.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel19.setText("Especialización:*");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 110, 40));

        cbxDispHoraria.setBackground(new java.awt.Color(204, 204, 204));
        cbxDispHoraria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "8:00-10:00", "10:00-12:00", "12:00-14:00" }));
        cbxDispHoraria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDispHorariaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxDispHoraria, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 140, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 70, 10));

        jLabel25.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel25.setText("Experiencia Laboral");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 120, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 650, 10));

        jLabel26.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel26.setText("Disponibilidad Horaria:* ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, 40));

        jLabel27.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel27.setText("Instituciones Anteriores:*");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, -1, 40));

        jLabel28.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel28.setText("Años de Experiencia:*");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, 40));

        txtInstiAnterior.setBackground(new java.awt.Color(204, 204, 204));
        txtInstiAnterior.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtInstiAnterior.setBorder(null);
        jPanel1.add(txtInstiAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 140, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 640, 10));

        jLabel30.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jLabel30.setText("Documentos Adjuntos");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 150, -1));

        jLabel31.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel31.setText("Curriculum Vitae:*");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, 40));

        jLabel32.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel32.setText("Certificados:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, -1, 40));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 70, 10));

        cbxEspecialización.setBackground(new java.awt.Color(204, 204, 204));
        cbxEspecialización.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Matematica", "Comunicacion", "Historia", "Desarrolllo Personal", "Ciencias", "Computacion" }));
        cbxEspecialización.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEspecializaciónActionPerformed(evt);
            }
        });
        jPanel1.add(cbxEspecialización, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 190, 30));

        btn_certificados.setBackground(new java.awt.Color(204, 204, 204));
        btn_certificados.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btn_certificados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/file-chart.png"))); // NOI18N
        btn_certificados.setText("Seleccionar Archivo");
        btn_certificados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(btn_certificados, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 180, 30));

        btn_curriculum.setBackground(new java.awt.Color(204, 204, 204));
        btn_curriculum.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btn_curriculum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/file-chart.png"))); // NOI18N
        btn_curriculum.setText("Seleccionar Archivo");
        btn_curriculum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(btn_curriculum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 170, 30));

        txtFecha.setBackground(new java.awt.Color(204, 204, 204));
        txtFecha.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        txtFecha.setBorder(null);
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 210, 30));

        check_certificado.setEnabled(false);
        check_certificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_certificadoActionPerformed(evt);
            }
        });
        jPanel1.add(check_certificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 610, 20, -1));

        check_curriculum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        check_curriculum.setEnabled(false);
        check_curriculum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_curriculumActionPerformed(evt);
            }
        });
        jPanel1.add(check_curriculum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void AgruparBotones(){
        groupSex=new ButtonGroup();
        groupSex.add(rbtnFem);
        groupSex.add(rbtnMas);
    }
    
    private void rbtnFemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnFemActionPerformed

    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPaisActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void cbxTipoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoDocActionPerformed

    private void txtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocActionPerformed

    private void cbxGrupoAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGrupoAcademicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGrupoAcademicoActionPerformed

    private void cbxDispHorariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDispHorariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDispHorariaActionPerformed

    private void cbxEspecializaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEspecializaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEspecializaciónActionPerformed

    private void check_certificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_certificadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_certificadoActionPerformed

    private void check_curriculumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_curriculumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_curriculumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btn_certificados;
    public javax.swing.JButton btn_curriculum;
    public javax.swing.JComboBox<String> cbxDispHoraria;
    public javax.swing.JComboBox<String> cbxEspecialización;
    public javax.swing.JComboBox<String> cbxGrupoAcademico;
    public javax.swing.JComboBox<String> cbxPais;
    public javax.swing.JComboBox<String> cbxTipoDoc;
    public javax.swing.JCheckBox check_certificado;
    public javax.swing.JCheckBox check_curriculum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JRadioButton rbtnFem;
    public javax.swing.JRadioButton rbtnMas;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtAñosExperiencia;
    public javax.swing.JTextField txtContacto;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtInstiAnterior;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtNumDoc;
    // End of variables declaration//GEN-END:variables
}
