/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author cr075
 */
public class RptHorario extends javax.swing.JInternalFrame {

    /**
     * Creates new form RgtEstudiante
     */
    public RptHorario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtCodBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnVerPrimero = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVerUltimo = new javax.swing.JButton();

        jButton4.setBackground(new java.awt.Color(102, 153, 255));
        jButton4.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/ordenar-por-opcion-de-boton-de-interfaz-de-atributos.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(true);

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(872, 736));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/logo_1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 90));

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 430, 40));

        jLabel4.setFont(new java.awt.Font("Swis721 Ex BT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reporte de Horario");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 610, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 860, 90));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 70, 10));

        jLabel3.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 510, 10));

        btnEliminar.setBackground(new java.awt.Color(102, 153, 255));
        btnEliminar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setOpaque(true);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 110, 30));

        jLabel6.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        jLabel6.setText("Ingrese Código de Horario a elegir: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 290, 20));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Num", "Código", "Cod. Salón", "Grado", "Sección", "Cod. Curso", "Nom. Curso", "DNI Profesor", "Nom. Prof.", "Día", "Hora Ini.", "Hor Fin."
            }
        ));
        jScrollPane3.setViewportView(tabla);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 880, 250));

        txtCodBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtCodBuscar.setBorder(null);
        jPanel1.add(txtCodBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 380, 30));

        btnBuscar.setBackground(new java.awt.Color(51, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(null);
        btnBuscar.setOpaque(true);
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 110, 30));

        btnVerPrimero.setBackground(new java.awt.Color(102, 153, 255));
        btnVerPrimero.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnVerPrimero.setForeground(new java.awt.Color(255, 255, 255));
        btnVerPrimero.setText("VER PRIMERO");
        btnVerPrimero.setBorder(null);
        btnVerPrimero.setOpaque(true);
        jPanel1.add(btnVerPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 110, 30));

        btnOrdenar.setBackground(new java.awt.Color(102, 153, 255));
        btnOrdenar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnOrdenar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img/ordenar-por-opcion-de-boton-de-interfaz-de-atributos.png"))); // NOI18N
        btnOrdenar.setBorder(null);
        btnOrdenar.setOpaque(true);
        jPanel1.add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 60, 30));

        btnEditar.setBackground(new java.awt.Color(102, 153, 255));
        btnEditar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("EDITAR");
        btnEditar.setBorder(null);
        btnEditar.setOpaque(true);
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 110, 30));

        btnVerUltimo.setBackground(new java.awt.Color(102, 153, 255));
        btnVerUltimo.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnVerUltimo.setForeground(new java.awt.Color(255, 255, 255));
        btnVerUltimo.setText("VER ÚLTIMO");
        btnVerUltimo.setBorder(null);
        btnVerUltimo.setOpaque(true);
        jPanel1.add(btnVerUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 900, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnOrdenar;
    public javax.swing.JButton btnVerPrimero;
    public javax.swing.JButton btnVerUltimo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtCodBuscar;
    // End of variables declaration//GEN-END:variables
}
